---
abstract: 'Parent class for AnyEvent-based objects'
author:
  - 'Mons Anderson <mons@cpan.org>'
  - 'Mons Anderson <mons@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Object
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  AnyEvent::Object:
    file: lib/AnyEvent/Object.pm
    version: 0.01
requires:
  perl: 5.8.8
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
